### PR TITLE
Fix Display of Faculty Notes when 'notes' is null - Meeting Modal

### LINKED ISSUE #331: Meeting Modal - Faculty Notes bugfix
When the notes of a faculty member is null, it should display "No Notes" under the faculty name in the meeting modal. This is currently not the case, because the code is checking only checking whether the 'notes' value is an empty string.

### PR DESCRIPTION
**Pull request by natalynyu**
This PR fixes a bug in which there is no note displayed under an individual faculty member in the meeting modal when faculty `notes` is `null.`. This was occurring because the previous code was only checking whether `notes` was equal (`===`) to an empty string and not considering the case when `notes` is equal to `null.` The fix makes it so that if `notes` is equal to `null`, the text 'No Notes' will be displayed under the faculty member.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to change)

## Checklist:

- [x] I have run `eslint` on the code
- [x] I have added JSDoc for all of my code (where applicable)
- [x] I have added tests to cover my changes.

## Priority:
- [x] Normal 
- [ ] High 

## Related Issues:

Fixes #331

### CODE REVIEW

File: src/client/components/pages/Courses/MeetingModal.tsx [hunk 1]
```diff
@@ -157,7 +157,7 @@ const MeetingModal: FunctionComponent<MeetingModalProps> = function ({
                     </h4>
                     <p>
                       {
-                        instructor.notes === ''
+                        !instructor.notes || instructor.notes === ''
```
Comment (rmainseas) [inline src/client/components/pages/Courses/MeetingModal.tsx:160]:
```suggestion
                        !instructor.notes
```

Since JavaScript considers `''` and `null` to both be a falsy values, you could probably get away with just the left side of the expression here.
image

**Review by rmainseas — CHANGES_REQUESTED** [review]
Looks great. :+1: 

Just one quick thing.

File: src/client/components/pages/Courses/MeetingModal.tsx (hunk 1 above)
Comment (natalynyu) [reply src/client/components/pages/Courses/MeetingModal.tsx]: Ah my bad! Thanks Robert.

**Review by rmainseas — APPROVED** [review]
Looks great. Merge away.
